### ISSUE TITLE
Improving test isolation in Workflow

### ISSUE THREAD

**Issue by matiassimon** [mochajs/mocha-examples#78]
**Summary:**

The current workflow runs all tests together in a single job, causing two main issues:

1. **Tracking Difficulty:**
   - It's challenging to distinguish which examples are functioning correctly and which aren't.

2. **Dependency Interference:**
   - Shared system dependencies might lead to misleading test results; an example might pass due to a dependency installed by a different example. 

**Proposed Solutions:**

1. **Matrix Strategy:**
   - Consider replacing Lerna with a matrix strategy in the workflow, iterating over each package's folder independently.

   ```yaml
   strategy:
     matrix:
       folder:
         - example1
         - example2
         - example3
       node-version:
         - 16
         - 18
   ```

2. **Separate Repositories:**
   - Alternatively, use individual repositories for each example, each with its own workflows. Add them as submodules to a main repository.
